
[functions.metric-tracker]
enabled = true
verify_jwt = true
import_map = "./functions/metric-tracker/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/metric-tracker/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/metric-tracker/*.html" ]

[storage.contest-videos]
public = true
file_size_limit = "100MB"
allowed_mime_types = [
  "video/mp4",
  "video/avi", 
  "video/mov",
  "video/wmv",
  "video/flv",
  "video/webm"
]
