name: Trigger Supabase Metric Tracker

on:
  workflow_dispatch: # Memungkinkan kita menjalankan manual dari tab Actions di GitHub
  schedule:
    # Menjalankan setiap jam, pada menit ke-0
    - cron: "0 * * * *"

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function URL
        # Menggunakan curl untuk memanggil fungsi dengan metode POST dan header Authorization
        run: |
          curl -X POST "${{ secrets.SUPABASE_FUNCTION_INVOKE_URL }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json"
